import raylibpy as rl

WIDTH = 1200
HEIGHT = 750
PADDING = HEIGHT // 25

# BUTTONS
BUTTON_WIDTH = WIDTH // 10
BUTTON_HEIGHT = HEIGHT // 20
BUTTON_COLOR = rl.LIGHTGRAY
HOVER_COLOR = rl.GRAY
TEXT_COLOR = rl.DARKGRAY
